### ISSUE TITLE
Issue about rollout.py

### ISSUE THREAD

**Issue by lfangyu09** [echowve/meshGraphNets_pytorch#4]
Hi,

When I run rollout.py, it shows " type object 'FPC' has no attribute 'datas_to_graph' ". After checking the FPY.py, I found that 'FPC' has no attribute 'datas_to_graph'. How can I solve this issue? 

Thanks,

**Comment by echowve** [comment]
Hi, I have fixed the problem, please check the newest code in this repo, thank you for your issue.
