### ISSUE TITLE
Rollout problem

### ISSUE THREAD

**Issue by fycAIwj** [echowve/meshGraphNets_pytorch#5]
Hello dear author, I would like to ask why in the code for prediction, the true value of the next moment is used as the input for rolling prediction, instead of using the predicted value as the input for rolling prediction.

**Comment by echowve** [comment]
The replaced value represents the boundary conditions of the flow field and is known beforehand.

**Comment by fycAIwj** [comment]
Dear Author
Thanks for your reply, your code is very useful.






发件人：Longxiang Jiang ***@***.***>
发送日期：2023-07-07 17:56:51
收件人：echowve/meshGraphNets_pytorch ***@***.***>
抄送人：fycAIwj ***@***.***>,Author ***@***.***>
主题：Re: [echowve/meshGraphNets_pytorch] Rollout problem (Issue #5)

The replaced value represents the boundary conditions of the flow field and is known beforehand.
