### ISSUE TITLE
Why no pressure output

### ISSUE THREAD

**Issue by Heiyanyan** [echowve/meshGraphNets_pytorch#8]
MGN says 'The network predicts change in momentum w , which is integrated once, and a direct prediction of the pressure
field p', however your code only predict the momentum, do I misunderstand something?

**Comment by BraveDrXuTF** [comment]
@Heiyanyan 
The same question, by the way, the original code in tf1 seems also have no pressure output.

> MGN says 'The network predicts change in momentum w , which is integrated once, and a direct prediction of the pressure field p', however your code only predict the momentum, do I misunderstand something?

**Comment by BraveDrXuTF** [comment]
> @Heiyanyan The same question, by the way, the original code in tf1 seems also have no pressure output.
> 
> > MGN says 'The network predicts change in momentum w , which is integrated once, and a direct prediction of the pressure field p', however your code only predict the momentum, do I misunderstand something?



> MGN says 'The network predicts change in momentum w , which is integrated once, and a direct prediction of the pressure field p', however your code only predict the momentum, do I misunderstand something?

I think i know the issue. You can just derive the pressure according to discretized ns-eq, thus, no need for predicting pressure, the pressure is calculated by hand.

**Comment by Heiyanyan** [comment]
understand, i think you are right, thank you very much!
